name: shell_uikit
description: A simple shell ui kit.
version: 0.3.0
homepage: https://fastforge.dev
repository: https://github.com/fastforgedev/fastforge/tree/main/packages/shell_uikit

environment:
  sdk: ">=2.16.0 <4.0.0"

dev_dependencies:
  dependency_validator: ^3.0.0
